### ISSUE TITLE
Could you please provide access to the required data files?

### ISSUE THREAD

**Issue by yangapku** [facebookresearch/vilbert-multi-task#1]
Hi! Thank you for releasing this great project! However, I notice that the data files (including the lmdb feature files as well as other metadata) needed to run pre-training and multi-task fine-tuning is not accessible. Could you please add accessible links to them? Or a readme guiding how to generate them is also fine. Thank you very much!

**Comment by vedanuj** [comment]
Hi @yangapku .. I have added a PR that includes files to do feature extraction and converting the extracted features to a LMDB file that can be used to train. 

Unfortunately we cannot make public the feature files at this point of time. It should be easy to extract features and use them after the Readme is updated. Stay tuned and monitor the PR for updates.

**Comment by yangapku** [comment]
Thank you for your reply! I will try to use the script to generate the feature files.

**Comment by yangapku** [comment]
Hi, could you please provide more details about the arguments for running the extract_features.py script, such as "num_features", "feature_name", "confidence_threshold" and "background"? Is using the default parameters the appropriate way? Thank you!

**Comment by vedanuj** [comment]
Yes using the default arguments should work for this project.

**Comment by yangapku** [comment]
Thanks! Do you mean that the default arguments work for preprocessing both the Conceptual Captions and the down-streaming datasets (COCO, VCR, etc.)? Meanwhile, I noticed that the arguments are different from the original ViL-BERT, like the increase in the number of boxes to 100 and the decrease in the confidence threshold to 0. Will that be okay?

**Comment by vedanuj** [comment]
For Conceptual Captions you can use number of boxes 36 and for downstream tasks it can be 100

**Comment by yangapku** [comment]
Thank you! May I ask another question? For VCR and RefCOCO, it's needed to generate features based on the given ground truth bounding boxes. In the original ViL-BERT, there is a `generate_tsv_gt.py` script for this case. How do I achieve this using the new feature extractor script?

**Comment by vedanuj** [comment]
Thanks for asking this. We will add that script as well.

**Comment by yangapku** [comment]
Hi, @vedanuj . May I ask is there any progress on including the script we've discussed before? Thank you!

**Comment by vedanuj** [comment]
@yangapku The scripts are added. Please check the readme in `data` directory. Let us know if you face any problems running the script.
