### ISSUE TITLE
trainval_ans2label.pkl?

### ISSUE THREAD

**Issue by Princesston** [facebookresearch/vilbert-multi-task#12]
Did anyone know where to find or how to generate the 'trainval_ans2label.pkl' required [here](https://github.com/facebookresearch/vilbert-multi-task/blob/76c96c6e063a04d77ea8ee09a527df20eb19929f/vilbert/datasets/vqa_dataset.py#L178)? Thanks a lot~

**Comment by vedanuj** [comment]
Please check this update #26  

Readme here : https://github.com/facebookresearch/vilbert-multi-task/tree/master/data

All the data for downstream tasks can be downloaded now.
