### ISSUE TITLE
errors when running fine tuning cmd

### ISSUE THREAD

**Issue by YupengGao** [facebookresearch/vilbert-multi-task#29]
I download your dataset and run:
 python train_tasks.py --bert_model bert-base-uncased --from_pretrained ./multi_task_model.bin --config_file config/bert_base_6layer_6conect.json --tasks 1 --lr_scheduler 'warmup_linear' --train_iter_gap 4 --task_specific_tokens --save_name finetune_from_multi_task_model

it will give error:
Traceback (most recent call last):
  File "train_tasks.py", line 670, in <module>
    main()
  File "train_tasks.py", line 529, in main
    task_losses,
  File "/dccstor/extrastore/vilbert-multi-task/vilbert/task_utils.py", line 197, in ForwardModelsTrain
    batch
ValueError: too many values to unpack (expected 9)

**Comment by KAndHisC** [comment]
I got this one in eval_retrieval.py

The error is :
Traceback (most recent call last):
  File "eval_retrieval.py", line 367, in <module>
    main()
  File "eval_retrieval.py", line 309, in main
    task_ids=task_tokens,
ValueError: too many values to unpack (expected 9)

and task_tokens is the  type of tensor([[19]], device='cuda:0')

**Comment by shivangibithel** [comment]
@KAndHisC  I got the same error in eval_retrieval.py.
How did you solve this?

**Comment by KAndHisC** [comment]
> @KAndHisC I got the same error in eval_retrieval.py.
> How did you solve this?
 
there is a little mistake in this [line](https://github.com/facebookresearch/vilbert-multi-task/blob/master/eval_retrieval.py#L299)
```
-                    _, _, vil_logit, _, _, _, _, _, _ = model(
+                    _, _, vil_logit, _, _, _, _, _, _, _ = model(
```

And you can also use my [repo](https://github.com/KAndHisC/vilbert-multi-task) as a reference. I'm still learning and maintaining this project recently.
