### ISSUE TITLE
Bug in Validation Logger

### ISSUE THREAD

**Issue by yashkant** [facebookresearch/vilbert-multi-task#5]
Hi, 

In the line below we aren't multiplying the score with batch-size, and while logging we are dividing the sum of scores with the complete dataset-size. Does this seem correct?

https://github.com/facebookresearch/vilbert-multi-task/blob/a290ba6d9c1c95375f622e66bfcdb666dd01ba89/vilbert/utils.py#L271

https://github.com/facebookresearch/vilbert-multi-task/blob/a290ba6d9c1c95375f622e66bfcdb666dd01ba89/vilbert/utils.py#L339

**Comment by vedanuj** [comment]
This is because the validation method `ForwardModelsVal ` returns a batch score (not divided by the batch size). Here : 

https://github.com/facebookresearch/vilbert-multi-task/blob/a290ba6d9c1c95375f622e66bfcdb666dd01ba89/vilbert/task_utils.py#L122-L163

**Comment by yashkant** [comment]
Oh, that makes sense! Thanks for explaining.
