### ISSUE TITLE
Trying to run demo

### ISSUE THREAD

**Issue by tranvansanghust** [facebookresearch/vilbert-multi-task#51]
I am trying to run demo file. But I can not find the config file (save/resnext_models/e2e_faster_rcnn_X-152-32x8d-FPN_1x_MLP_2048_FPN_512_train.yaml ) and model file (save/resnext_models/model_final.pth). Can anyone help me? Thank you so much.

**Comment by goonmeet** [comment]
Hi!
 
How did you solve this issue?

Thanks!

**Comment by TSorzZZ** [comment]
Hi,How you solve this problem ，can you tell me？

**Comment by WannaGetDSJobInSanFrancisco** [comment]
Hi, #6 seems to be related - found config file in the mentioned repository and tools/c2_to_pt.py is dedicated to generate model_final.pth. Hope this works.
