### ISSUE TITLE
Where can I find visual genome's object categories?

### ISSUE THREAD

**Issue by juliuswang0728** [facebookresearch/vilbert-multi-task#55]
Hi! 

I'm trying to extract features on Conceptual Captions with [script/extract_features.py](https://github.com/facebookresearch/vilbert-multi-task/blob/master/script/extract_features.py), while the output `.npy` file contains also the class predictions, I wonder could you also provide the indices corresponding to those 1,600 object categories in Visual Genome? (such as [this](https://github.com/peteanderson80/bottom-up-attention/blob/master/data/genome/1600-400-20/objects_vocab.txt) or [this](https://dl.fbaipublicfiles.com/pythia/data/visual_genome_categories.json))

Thanks!

**Comment by juliuswang0728** [comment]
Sorry there was a mistake in my code, [this json file](https://dl.fbaipublicfiles.com/pythia/data/visual_genome_categories.json) perfectly serves the purpose! Closing this now.

**Comment by ttaoREtw** [comment]
Is the index 0 stands for "background"?
Thank you in advance.

**Comment by juliuswang0728** [comment]
Yes I think so.
