### ISSUE TITLE
Non-existent config key error?

### ISSUE THREAD

**Issue by Princesston** [facebookresearch/vilbert-multi-task#6]
Hi, I got `KeyError: 'Non-existent config key: MODEL.BACKBONE.OUT_CHANNELS'` when ran the `extract_features.py` file. I was wondering if you know the possible reason (I downloaded the model and config file using the given link)? Thanks for the work, btw

**Comment by HubHop** [comment]
Hi, I got the same error, I fixed it by installing maskrcnn from this repo instead:
https://gitlab.com/vedanuj/vqa-maskrcnn-benchmark/tree/master,

cd vqa-maskrcnn-benchmark
python setup.py build develop
