### ISSUE TITLE
training_feat_all.lmdb and caption_train.json not found

### ISSUE THREAD

**Issue by HubHop** [facebookresearch/vilbert-multi-task#7]
Hi, thanks for your excellent work.

I'm trying to run your code with [Pretraining on Conceptual Captions](https://github.com/facebookresearch/vilbert-multi-task#pretraining-on-conceptual-captions), but some files do not exist, and I didn't find any script to generate them. I've tried to set up data as specified [here](https://github.com/facebookresearch/vilbert-multi-task/tree/master/data#extracting-features), but the step 3 only gives me a `data.mdb` and a `lock.mdb`. Can you provide `training_feat_all.lmdb` and `caption_train.json` ?

Many thanks.

**Comment by yangapku** [comment]
The `training_feat_all.lmdb` should be the name of the directory storing `data.mdb` and `lock.mdb`.

**Comment by HubHop** [comment]
Hi @yangapku , thanks a lot, it works. But how do you prepare `caption_train.json`?

**Comment by vedanuj** [comment]
Hi @HubHop 

For `caption_train.json` you will need to download the captions for Conceptual Captions dataset.

**Comment by YupengGao** [comment]
Can you provide more details on how to generate caption_train.json? what's the format? and which part pf code was used to link the caption and image feature together during trainning?

**Comment by zaynmi** [comment]
@HubHop Hi, where could I get the `caption_train.json`? Conceptual Captions dataset only provide .tsv files officially. Or should I generate images and captions by myself?

**Comment by HubHop** [comment]
Hi @zaynmi, I prepared my data based on this script:
https://github.com/jackroos/VL-BERT/blob/master/data/conceptual-captions/ReadMe.txt

Cheers

**Comment by leyuan** [comment]
Hi @HubHop what did you get after generating the Json? I got a weird format:
```
{"image": "val_image.zip@/00000000.jpg", "caption": ["author", ":", "a", "life", "in", "photography", "--", "in", "pictures"]}
{"image": "val_image.zip@/00000002.jpg", "caption": ["photograph", "of", "the", "sign", "being", "repaired", "by", "brave", "person"]}
{"image": "val_image.zip@/00000003.jpg", "caption": ["the", "player", "staring", "intently", "at", "a", "computer", "screen", "."]}
```

Did you get the `caption_train.py` work? Thanks.

**Comment by MrWuZhonghua** [comment]
> @HubHop Hi, where could I get the `caption_train.json`? Conceptual Captions dataset only provide .tsv files officially. Or should I generate images and captions by myself?

Have you found the caption_train.json? I still haven't found. Thanks

**Comment by MrWuZhonghua** [comment]
> Hi @HubHop what did you get after generating the Json? I got a weird format:
> 
> ```
> {"image": "val_image.zip@/00000000.jpg", "caption": ["author", ":", "a", "life", "in", "photography", "--", "in", "pictures"]}
> {"image": "val_image.zip@/00000002.jpg", "caption": ["photograph", "of", "the", "sign", "being", "repaired", "by", "brave", "person"]}
> {"image": "val_image.zip@/00000003.jpg", "caption": ["the", "player", "staring", "intently", "at", "a", "computer", "screen", "."]}
> ```
> 
> Did you get the `caption_train.py` work? Thanks.

Have you found the caption_train.json? I still haven't found. Thanks

**Comment by MrWuZhonghua** [comment]
@leyuan @zaynmi Hi, have you found the caption_train.json files? Can you please tell me how to get it? Thanks
