### ISSUE TITLE
GQA Data

### ISSUE THREAD

**Issue by goonmeet** [facebookresearch/vilbert-multi-task#72]
Hi!

Where can I find all of the data (e.g., all the .pkl files) for the GQA dataset?

Thanks in advance!

**Comment by mikelmrtinez** [comment]
Hello! 

I'm facing the same problem. How did you solve it?

Thanks in advance!

**Comment by goonmeet** [comment]
Hi!

So it turns out that you have to down the big dataset file and then also download the GQA specific data. 

As per the readme:

cd data
wget https://dl.fbaipublicfiles.com/vilbert-multi-task/datasets.tar.gz
tar xf datasets.tar.gz

This is a really big file so make sure your system can handle it!

cd gqa

mkdir gqa_resnext152_faster_rcnn_genome.lmdb

cd gqa_resnext152_faster_rcnn_genome.lmdb

wget https://dl.fbaipublicfiles.com/vilbert-multi-task/datasets/gqa/gqa_resnext152_faster_rcnn_genome.lmdb/data.mdb

**Comment by mikelmrtinez** [comment]
Hi!

Thank you for your reply, it has been very helpful.

Best regards,
Mikel
